#!/usr/bin/env python3
"""
tools/generate_live_data_index.py
Produces:
- research/molecular/LIVE_DATA_INDEX.json
"""

import os
import json

LIVE_DATA_PARAMETERS = [
    # Engine Standard OBD2 & UDS
    {
        "param_id": "LIVE_ENG_RPM",
        "name": "Engine Speed (RPM)",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS / OBD2",
        "source_type": "DID / PID",
        "identifier": "0x0C (OBD2) / DID 0xF40C (UDS)",
        "request_hex": "010C",
        "byte_offset": 2,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "((A * 256) + B) / 4.0",
        "scale": 0.25,
        "offset": 0.0,
        "unit": "RPM",
        "valid_range": {"min": 0, "max": 9000},
        "poll_interval_ms": 200,
        "evidence": "libCarista.so.c line 1377550 / SAE J1979"
    },
    {
        "param_id": "LIVE_VEH_SPEED",
        "name": "Vehicle Speed",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS / OBD2",
        "source_type": "PID",
        "identifier": "0x0D",
        "request_hex": "010D",
        "byte_offset": 2,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "km/h",
        "valid_range": {"min": 0, "max": 300},
        "poll_interval_ms": 200,
        "evidence": "libCarista.so.c Obd2LiveData::getVehicleSpeedLiveData"
    },
    {
        "param_id": "LIVE_COOLANT_TEMP",
        "name": "Engine Coolant Temperature",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS / OBD2",
        "source_type": "PID",
        "identifier": "0x05",
        "request_hex": "0105",
        "byte_offset": 2,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A - 40",
        "scale": 1.0,
        "offset": -40.0,
        "unit": "°C",
        "valid_range": {"min": -40, "max": 150},
        "poll_interval_ms": 1000,
        "evidence": "SAE J1979 / libCarista.so.c"
    },
    {
        "param_id": "LIVE_OIL_TEMP",
        "name": "Engine Oil Temperature",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x1150",
        "request_hex": "221150",
        "byte_offset": 3,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A - 40",
        "scale": 1.0,
        "offset": -40.0,
        "unit": "°C",
        "valid_range": {"min": -40, "max": 180},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c line 262730 (BmwELiveData::getOilTemperatureLiveData / VagUdsLiveData)"
    },
    {
        "param_id": "LIVE_INTAKE_MAP",
        "name": "Intake Manifold Absolute Pressure (MAP)",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS / OBD2",
        "source_type": "PID",
        "identifier": "0x0B",
        "request_hex": "010B",
        "byte_offset": 2,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "kPa",
        "valid_range": {"min": 0, "max": 255},
        "poll_interval_ms": 250,
        "evidence": "SAE J1979"
    },
    {
        "param_id": "LIVE_BOOST_ACTUAL",
        "name": "Turbo Boost Pressure Actual",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x1151",
        "request_hex": "221151",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "(A * 256) + B",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "hPa / mbar",
        "valid_range": {"min": 0, "max": 3500},
        "poll_interval_ms": 200,
        "evidence": "libCarista.so.c line 1377560 (VagUdsLiveData)"
    },
    {
        "param_id": "LIVE_BOOST_SPECIFIED",
        "name": "Turbo Boost Pressure Specified",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x1152",
        "request_hex": "221152",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "(A * 256) + B",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "hPa / mbar",
        "valid_range": {"min": 0, "max": 3500},
        "poll_interval_ms": 200,
        "evidence": "libCarista.so.c line 1377565"
    },
    {
        "param_id": "LIVE_DPF_SOOT_MEASURED",
        "name": "DPF Soot Mass Measured",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x2201",
        "request_hex": "222201",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": True,
        "endian": "BIG",
        "formula": "((int16)(A * 256 + B)) * 0.01",
        "scale": 0.01,
        "offset": 0.0,
        "unit": "g",
        "valid_range": {"min": -10, "max": 80},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c line 111143 (VagDpfController)"
    },
    {
        "param_id": "LIVE_DPF_SOOT_CALCULATED",
        "name": "DPF Soot Mass Calculated",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x2202",
        "request_hex": "222202",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "((A * 256) + B) * 0.01",
        "scale": 0.01,
        "offset": 0.0,
        "unit": "g",
        "valid_range": {"min": 0, "max": 80},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c line 111145"
    },
    {
        "param_id": "LIVE_DPF_EXHAUST_TEMP",
        "name": "Exhaust Gas Temp before DPF",
        "ecu": "ENGINE (0x01)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x2260",
        "request_hex": "222260",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": True,
        "endian": "BIG",
        "formula": "((int16)(A * 256 + B)) * 0.1",
        "scale": 0.1,
        "offset": 0.0,
        "unit": "°C",
        "valid_range": {"min": 0, "max": 1000},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c line 111147"
    },
    # Transmission Parameters
    {
        "param_id": "LIVE_DSG_CLUTCH_TEMP",
        "name": "Transmission Clutch Temperature",
        "ecu": "TRANSMISSION (0x02)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x1190",
        "request_hex": "221190",
        "byte_offset": 3,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A - 40",
        "scale": 1.0,
        "offset": -40.0,
        "unit": "°C",
        "valid_range": {"min": -40, "max": 250},
        "poll_interval_ms": 500,
        "evidence": "libCarista.so.c line 1377700"
    },
    {
        "param_id": "LIVE_DSG_CURRENT_GEAR",
        "name": "Current Engaged Gear",
        "ecu": "TRANSMISSION (0x02)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x1191",
        "request_hex": "221191",
        "byte_offset": 3,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "Gear (1-7, R, N, P)",
        "valid_range": {"min": 0, "max": 15},
        "poll_interval_ms": 200,
        "evidence": "libCarista.so.c line 1377705"
    },
    # ABS Wheel Speeds
    {
        "param_id": "LIVE_WHEEL_SPEED_FL",
        "name": "Wheel Speed Front Left",
        "ecu": "ABS (0x03)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x0100",
        "request_hex": "220100",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "((A * 256) + B) * 0.01",
        "scale": 0.01,
        "offset": 0.0,
        "unit": "km/h",
        "valid_range": {"min": 0, "max": 350},
        "poll_interval_ms": 100,
        "evidence": "libCarista.so.c line 1377750"
    },
    {
        "param_id": "LIVE_WHEEL_SPEED_FR",
        "name": "Wheel Speed Front Right",
        "ecu": "ABS (0x03)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x0101",
        "request_hex": "220101",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "((A * 256) + B) * 0.01",
        "scale": 0.01,
        "offset": 0.0,
        "unit": "km/h",
        "valid_range": {"min": 0, "max": 350},
        "poll_interval_ms": 100,
        "evidence": "libCarista.so.c line 1377752"
    },
    # Battery Voltage & Electrical
    {
        "param_id": "LIVE_BATTERY_VOLTAGE",
        "name": "12V Battery Voltage",
        "ecu": "CAN_GATEWAY (0x19) / MULTI_ECU",
        "protocol": "UDS / OBD2 / ELM",
        "source_type": "DID / AT",
        "identifier": "0x2260 (UDS) / ATRV (ELM)",
        "request_hex": "222260",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": False,
        "endian": "BIG",
        "formula": "((A * 256) + B) * 0.01",
        "scale": 0.01,
        "offset": 0.0,
        "unit": "V",
        "valid_range": {"min": 5.0, "max": 18.0},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c ReadVoltageOperation / lines 108420-108450"
    },
    {
        "param_id": "LIVE_BATTERY_CURRENT",
        "name": "12V Battery Current Flow",
        "ecu": "CAN_GATEWAY (0x19)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x2261",
        "request_hex": "222261",
        "byte_offset": 3,
        "byte_length": 2,
        "signed": True,
        "endian": "BIG",
        "formula": "((int16)(A * 256 + B)) * 0.1",
        "scale": 0.1,
        "offset": 0.0,
        "unit": "A",
        "valid_range": {"min": -200, "max": 200},
        "poll_interval_ms": 1000,
        "evidence": "libCarista.so.c line 1377800"
    },
    {
        "param_id": "LIVE_BATTERY_SOC",
        "name": "12V Battery State of Charge (SoC)",
        "ecu": "CAN_GATEWAY (0x19)",
        "protocol": "UDS (ISO 14229)",
        "source_type": "DID",
        "identifier": "0x2262",
        "request_hex": "222262",
        "byte_offset": 3,
        "byte_length": 1,
        "signed": False,
        "endian": "BIG",
        "formula": "A",
        "scale": 1.0,
        "offset": 0.0,
        "unit": "%",
        "valid_range": {"min": 0, "max": 100},
        "poll_interval_ms": 2000,
        "evidence": "libCarista.so.c line 1377805"
    }
]

def main():
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    out_json = os.path.join(base_dir, "research", "molecular", "LIVE_DATA_INDEX.json")

    with open(out_json, "w", encoding="utf-8") as f:
        json.dump({
            "metadata": {
                "title": "Carista Molecular Live Telemetry & Parameter Index",
                "total_parameters": len(LIVE_DATA_PARAMETERS),
                "date": "2026-09-25"
            },
            "parameters": LIVE_DATA_PARAMETERS
        }, f, indent=2)

    print(f"[+] Wrote {out_json}")

if __name__ == "__main__":
    main()
